Repository jenkinsci/pipeline-cps-http-plugin, pull requests merged in 2025-01, with the labels that each got.

#18 Build on Java 17 and 21
  Jenkinsfile
  pom.xml
Labels: developer

#19 Require 2.479.1 and Java 17
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflowhttp/cps/CpsHttpFlowDefinition.java
Labels: dependencies

#23 Update documentation and remove duplicated dependency
  README.md
  example.png
  pom.xml
Labels: documentation

#25 Fix typo
  README.md
Labels: documentation

#24 Applied recipe AddCodeOwner
  .github/CODEOWNERS
Labels: chore

#20 Enable CD
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
  release.properties
Labels: chore

#26 Spotless format
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflowhttp/cps/CacheEntry.java
  src/main/java/org/jenkinsci/plugins/workflowhttp/cps/CachingConfiguration.java
  src/main/java/org/jenkinsci/plugins/workflowhttp/cps/CpsHttpFlowDefinition.java
  src/main/java/org/jenkinsci/plugins/workflowhttp/cps/RobustHTTPClient.java
  src/test/java/org/jenkinsci/plugins/workflowhttp/cps/CachingConfigurationTest.java
  src/test/java/org/jenkinsci/plugins/workflowhttp/cps/CpsHttpFlowDefinitionTest.java
Labels: chore

#27 Git blame ignore for spotless revision
  .git-blame-ignore-revs
Labels: chore

#30 Add Help Text for Credentials, Key Header, and Value Header Fields
  src/main/resources/org/jenkinsci/plugins/workflowhttp/cps/CpsHttpFlowDefinition/help-credentialsId.html
  src/main/resources/org/jenkinsci/plugins/workflowhttp/cps/CpsHttpFlowDefinition/help-setKeyHeader.html
  src/main/resources/org/jenkinsci/plugins/workflowhttp/cps/CpsHttpFlowDefinition/help-setValueHeader.html
Labels: chore
